# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: 'docs|.git|.tox'
default_stages: [commit]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: detect-private-key
          - id: fix-byte-order-marker
          - id: check-yaml
          - id: check-json
          - id: check-toml
          - id: check-xml
          - id: check-symlinks
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-docstring-first
          - id: check-added-large-files
          - id: check-executables-have-shebangs

    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            exclude: ^starlette_boot/components/

    - repo: https://github.com/psf/black.git
      rev: 22.10.0
      hooks:
          - id: black
            exclude: ^starlette_boot/components/

    -   repo: https://github.com/humitos/mirrors-autoflake.git
        rev: v1.3
        hooks:
            -   id: autoflake
                exclude: ^starlette_boot/components/
                args: [ '--in-place', '--remove-all-unused-imports', '--remove-unused-variable' ]


    - repo: https://github.com/pycqa/flake8
      rev: 5.0.4
      hooks:
          - id: flake8
            exclude: ^starlette_boot/components/

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.990'
      hooks:
          - id: mypy
            exclude: ^starlette_boot/components/
            additional_dependencies:
                - types-python-slugify

    -   repo: https://github.com/myint/docformatter.git
        rev: v1.5.0
        hooks:
            -   id: docformatter
                exclude: ^starlette_boot/components/
                args: [ '--in-place', '--wrap-summaries=120', '--wrap-descriptions=120', '--pre-summary-newline' ]
